pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: squash
  - name: Automatic update to the main branch for pull requests
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update:
