[package]
name = "fake_package"
version = "0.1.0"
edition.workspace = true
publish = false
license.workspace = true

[lints]
workspace = true

[dependencies]
cargo_utils = { path = "../cargo_utils", version = "0.1"}
cargo_metadata.workspace = true
serde_json.workspace = true
