[package]
name = "fake_package"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
cargo_utils = { path = "../cargo_utils", version = "0.1"}
cargo_metadata.workspace = true
serde_json.workspace = true
