[book]
authors = ["Marco Ieni"]
language = "en"
multilingual = false
title = "Release-plz"
description = "Release rust packages without using the command line."

[output.html]
git-repository-url = "https://github.com/MarcoIeni/release-plz"
edit-url-template = "https://github.com/MarcoIeni/release-plz/edit/main/docs/{path}"
site-url = "/release-plz/"
