name: Book CD # Continuous Deployment

permissions:
  contents: write

on:
  workflow_dispatch:  # Allow manual triggers
  push:
    tags:
      - "release-plz-v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
      - run: mdbook build docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
