name: Links

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - "release-plz*"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
